# -*- coding: utf-8 -*-
"""Betting Website(Client)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsplaFUbSZleNE236iEtLA8nl7SK7aMG
"""

!pip install -q fastapi "uvicorn[standard]" jinja2 python-multipart
!apt-get -qq update
!apt-get -qq install -y curl

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared
!chmod +x /usr/local/bin/cloudflared
!/usr/local/bin/cloudflared --version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/app.py
# from fastapi import FastAPI, Request, Form
# from fastapi.responses import HTMLResponse, RedirectResponse
# from fastapi.templating import Jinja2Templates
# from datetime import datetime
# import uuid
# 
# app = FastAPI(title="NBA Betting Platform")
# templates = Jinja2Templates(directory="templates")
# 
# ADMIN_PASSWORD = "admin123"
# PLATFORM_FEE_RATE = 0.05
# MIN_BET = 1000
# 
# game_state = {
#     "team_a": "Lakers",
#     "team_b": "Celtics",
#     "score_a": 0,
#     "score_b": 0,
#     "quarter": "Not Started",
#     "status": "Open for Betting",
#     "winner": "",
#     "settled_at": "",
# }
# 
# players = {}
# bets = {}
# results = {}
# 
# def money(v):
#     try:
#         return f"₱{float(v):,.2f}"
#     except Exception:
#         return "₱0.00"
# 
# def now_str():
#     return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
# 
# def generate_code():
#     return str(uuid.uuid4())[:8].upper()
# 
# def pot():
#     return sum(b["bet_amount"] for b in bets.values()) if bets else 0.0
# 
# def total_fee_collected():
#     return sum(r.get("fee", 0.0) for r in results.values()) if results else 0.0
# 
# def total_final_payouts():
#     return sum(r.get("final_payout", 0.0) for r in results.values()) if results else 0.0
# 
# def public_summary():
#     return {
#         "matchup": f"{game_state['team_a']} vs {game_state['team_b']}",
#         "score": f"{game_state['score_a']} - {game_state['score_b']}",
#         "quarter": game_state["quarter"],
#         "status": game_state["status"],
#         "pot": money(pot()),
#         "players_with_bets": len(bets),
#     }
# 
# def validate_admin(password: str) -> bool:
#     return password == ADMIN_PASSWORD
# 
# def settle_game(winner: str):
#     global results
#     results = {}
# 
#     if not bets:
#         game_state["winner"] = winner
#         game_state["status"] = "Settled"
#         game_state["settled_at"] = now_str()
#         return
# 
#     total_winning_bets = sum(b["bet_amount"] for b in bets.values() if b["team"] == winner)
#     total_losing_bets = sum(b["bet_amount"] for b in bets.values() if b["team"] != winner)
# 
#     for code, b in bets.items():
#         bet_amount = float(b["bet_amount"])
# 
#         if b["team"] == winner and total_winning_bets > 0:
#             share = bet_amount / total_winning_bets
#             gross_profit = share * total_losing_bets
#             fee = gross_profit * PLATFORM_FEE_RATE
#             net_profit = gross_profit - fee
#             final_payout = bet_amount + net_profit
# 
#             results[code] = {
#                 "name": b["name"],
#                 "team": b["team"],
#                 "bet_amount": round(bet_amount, 2),
#                 "status": "WIN",
#                 "gross_profit": round(gross_profit, 2),
#                 "fee": round(fee, 2),
#                 "net_profit": round(net_profit, 2),
#                 "final_payout": round(final_payout, 2),
#             }
#         else:
#             results[code] = {
#                 "name": b["name"],
#                 "team": b["team"],
#                 "bet_amount": round(bet_amount, 2),
#                 "status": "LOSE",
#                 "gross_profit": 0.0,
#                 "fee": 0.0,
#                 "net_profit": round(-bet_amount, 2),
#                 "final_payout": 0.0,
#             }
# 
#     game_state["winner"] = winner
#     game_state["status"] = "Settled"
#     game_state["settled_at"] = now_str()
# 
# @app.get("/", response_class=HTMLResponse)
# async def home(request: Request):
#     return templates.TemplateResponse("home.html", {
#         "request": request,
#         "summary": public_summary(),
#     })
# 
# @app.get("/admin", response_class=HTMLResponse)
# async def admin_page(request: Request, msg: str = ""):
#     base_url = str(request.base_url).rstrip("/")
#     player_links = []
#     for code, p in players.items():
#         player_links.append({
#             "name": p["name"],
#             "code": code,
#             "link": f"{base_url}/player/{code}",
#             "created_at": p["created_at"],
#         })
# 
#     all_bets = []
#     for code, b in bets.items():
#         all_bets.append({
#             "code": code,
#             "name": b["name"],
#             "team": b["team"],
#             "bet_amount": money(b["bet_amount"]),
#             "time_added": b["time_added"],
#         })
# 
#     all_results = []
#     for code, r in results.items():
#         all_results.append({
#             "code": code,
#             "name": r["name"],
#             "team": r["team"],
#             "bet_amount": money(r["bet_amount"]),
#             "status": r["status"],
#             "gross_profit": money(r["gross_profit"]),
#             "fee": money(r["fee"]),
#             "net_profit": money(r["net_profit"]),
#             "final_payout": money(r["final_payout"]),
#         })
# 
#     return templates.TemplateResponse("admin.html", {
#         "request": request,
#         "summary": public_summary(),
#         "game_state": game_state,
#         "msg": msg,
#         "registered_players": len(players),
#         "players_with_bets": len(bets),
#         "total_pot": money(pot()),
#         "admin_fees": money(total_fee_collected()),
#         "total_payouts": money(total_final_payouts()),
#         "player_links": player_links,
#         "all_bets": all_bets,
#         "all_results": all_results,
#     })
# 
# @app.post("/admin/set_game")
# async def admin_set_game(
#     password: str = Form(...),
#     team_a: str = Form(...),
#     team_b: str = Form(...),
# ):
#     if not validate_admin(password):
#         return RedirectResponse("/admin?msg=Invalid+admin+password", status_code=303)
# 
#     a = team_a.strip()
#     b = team_b.strip()
# 
#     if not a or not b or a.lower() == b.lower():
#         return RedirectResponse("/admin?msg=Enter+two+different+team+names", status_code=303)
# 
#     game_state["team_a"] = a
#     game_state["team_b"] = b
#     game_state["score_a"] = 0
#     game_state["score_b"] = 0
#     game_state["quarter"] = "Not Started"
#     game_state["status"] = "Open for Betting"
#     game_state["winner"] = ""
#     game_state["settled_at"] = ""
# 
#     return RedirectResponse("/admin?msg=Game+updated", status_code=303)
# 
# @app.post("/admin/update_score")
# async def admin_update_score(
#     password: str = Form(...),
#     score_a: int = Form(...),
#     score_b: int = Form(...),
#     quarter: str = Form(...),
#     status: str = Form(...),
# ):
#     if not validate_admin(password):
#         return RedirectResponse("/admin?msg=Invalid+admin+password", status_code=303)
# 
#     game_state["score_a"] = score_a
#     game_state["score_b"] = score_b
#     game_state["quarter"] = quarter
#     game_state["status"] = status
# 
#     return RedirectResponse("/admin?msg=Scoreboard+updated", status_code=303)
# 
# @app.post("/admin/create_player")
# async def admin_create_player(
#     password: str = Form(...),
#     player_name: str = Form(...),
# ):
#     if not validate_admin(password):
#         return RedirectResponse("/admin?msg=Invalid+admin+password", status_code=303)
# 
#     name = player_name.strip()
#     if not name:
#         return RedirectResponse("/admin?msg=Player+name+is+required", status_code=303)
# 
#     code = generate_code()
#     players[code] = {
#         "name": name,
#         "created_at": now_str(),
#     }
# 
#     return RedirectResponse("/admin?msg=Player+created", status_code=303)
# 
# @app.post("/admin/settle")
# async def admin_settle(
#     password: str = Form(...),
#     winner: str = Form(...),
# ):
#     if not validate_admin(password):
#         return RedirectResponse("/admin?msg=Invalid+admin+password", status_code=303)
# 
#     if winner not in [game_state["team_a"], game_state["team_b"]]:
#         return RedirectResponse("/admin?msg=Invalid+winner", status_code=303)
# 
#     settle_game(winner)
#     return RedirectResponse("/admin?msg=Game+settled", status_code=303)
# 
# @app.get("/player/{access_code}", response_class=HTMLResponse)
# async def player_page(request: Request, access_code: str, msg: str = ""):
#     code = access_code.strip().upper()
# 
#     if code not in players:
#         return templates.TemplateResponse("invalid_player.html", {
#             "request": request,
#             "code": code,
#         }, status_code=404)
# 
#     player = players[code]
#     player_bet = bets.get(code)
#     player_result = results.get(code)
# 
#     return templates.TemplateResponse("player.html", {
#         "request": request,
#         "summary": public_summary(),
#         "game_state": game_state,
#         "code": code,
#         "player": player,
#         "player_bet": player_bet,
#         "player_result": player_result,
#         "money": money,
#         "msg": msg,
#         "min_bet": MIN_BET,
#     })
# 
# @app.post("/player/{access_code}/bet")
# async def player_bet(
#     access_code: str,
#     selected_team: str = Form(...),
#     bet_amount: float = Form(...),
# ):
#     code = access_code.strip().upper()
# 
#     if code not in players:
#         return RedirectResponse(f"/player/{code}", status_code=303)
# 
#     if game_state["status"] != "Open for Betting":
#         return RedirectResponse(f"/player/{code}?msg=Betting+is+closed", status_code=303)
# 
#     if selected_team not in [game_state["team_a"], game_state["team_b"]]:
#         return RedirectResponse(f"/player/{code}?msg=Invalid+team+selection", status_code=303)
# 
#     if bet_amount < MIN_BET:
#         return RedirectResponse(f"/player/{code}?msg=Minimum+bet+is+PHP+1000", status_code=303)
# 
#     bets[code] = {
#         "name": players[code]["name"],
#         "team": selected_team,
#         "bet_amount": bet_amount,
#         "time_added": now_str(),
#     }
# 
#     return RedirectResponse(f"/player/{code}?msg=Bet+saved+successfully", status_code=303)

import os, textwrap

os.makedirs("/content/templates", exist_ok=True)

base_html = r"""
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>NBA Betting Platform</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    :root{
      --bg:#050816;
      --panel:#0b1220;
      --panel-2:#111a2b;
      --line:rgba(255,255,255,.08);
      --text:#eef4ff;
      --muted:#9fb0d0;
      --blue:#4f7cff;
      --blue-2:#6ea8ff;
      --glow:0 0 0 1px rgba(110,168,255,.10), 0 20px 60px rgba(43,89,255,.18);
      --radius:22px;
    }

    *{box-sizing:border-box}
    body{
      margin:0;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
      background:
        radial-gradient(circle at top right, rgba(79,124,255,.18), transparent 28%),
        radial-gradient(circle at bottom left, rgba(79,124,255,.12), transparent 22%),
        linear-gradient(180deg, #040814 0%, #07101e 100%);
      color:var(--text);
    }

    .app-shell{
      display:grid;
      grid-template-columns: 250px 1fr;
      min-height:100vh;
      gap:18px;
      padding:18px;
    }

    .sidebar{
      background:linear-gradient(180deg, rgba(14,21,38,.95), rgba(7,12,24,.98));
      border:1px solid var(--line);
      border-radius:28px;
      padding:20px 16px;
      box-shadow:var(--glow);
      position:sticky;
      top:18px;
      height:calc(100vh - 36px);
    }

    .brand{
      display:flex;
      align-items:center;
      gap:10px;
      font-weight:700;
      font-size:20px;
      margin-bottom:18px;
    }

    .brand-badge{
      width:34px;height:34px;border-radius:12px;
      background:linear-gradient(135deg, var(--blue), #8ab7ff);
      box-shadow:0 10px 30px rgba(79,124,255,.35);
    }

    .nav-card{
      background:rgba(255,255,255,.03);
      border:1px solid var(--line);
      border-radius:22px;
      padding:18px;
      margin-bottom:18px;
    }

    .nav-title{
      color:var(--muted);
      font-size:12px;
      letter-spacing:.08em;
      text-transform:uppercase;
      margin-bottom:10px;
    }

    .nav-big{
      font-size:32px;
      font-weight:800;
      line-height:1;
      margin:8px 0;
    }

    .nav-sub{
      color:var(--muted);
      font-size:14px;
    }

    .nav-links{
      display:flex;
      flex-direction:column;
      gap:8px;
      margin-top:14px;
    }

    .nav-links a{
      text-decoration:none;
      color:#d9e4ff;
      padding:12px 14px;
      border-radius:14px;
      background:transparent;
      border:1px solid transparent;
      transition:.2s ease;
      display:block;
    }

    .nav-links a:hover{
      background:rgba(79,124,255,.10);
      border-color:rgba(79,124,255,.22);
    }

    .main{
      display:flex;
      flex-direction:column;
      gap:18px;
    }

    .topbar{
      display:flex;
      align-items:center;
      justify-content:space-between;
      gap:16px;
      background:linear-gradient(180deg, rgba(9,14,27,.88), rgba(8,13,24,.98));
      border:1px solid var(--line);
      border-radius:24px;
      padding:16px 20px;
      box-shadow:var(--glow);
    }

    .page-title{
      font-size:28px;
      font-weight:800;
      letter-spacing:-.03em;
    }

    .page-sub{
      color:var(--muted);
      font-size:14px;
      margin-top:4px;
    }

    .pill{
      padding:10px 14px;
      border-radius:14px;
      background:rgba(255,255,255,.04);
      border:1px solid var(--line);
      color:#dbe6ff;
      font-size:14px;
    }

    .hero-grid{
      display:grid;
      grid-template-columns:repeat(4, 1fr);
      gap:18px;
    }

    .metric{
      background:linear-gradient(180deg, rgba(8,15,31,.96), rgba(6,11,22,.96));
      border:1px solid var(--line);
      border-radius:24px;
      padding:20px;
      box-shadow:var(--glow);
      position:relative;
      overflow:hidden;
    }

    .metric:before{
      content:"";
      position:absolute;
      inset:auto -40px -40px auto;
      width:120px;
      height:120px;
      background:radial-gradient(circle, rgba(79,124,255,.30), transparent 65%);
      pointer-events:none;
    }

    .metric-label{
      color:var(--muted);
      font-size:13px;
      margin-bottom:12px;
    }

    .metric-value{
      font-size:30px;
      font-weight:800;
      letter-spacing:-.04em;
    }

    .metric-note{
      color:#b8c7e6;
      font-size:13px;
      margin-top:8px;
    }

    .grid-2{
      display:grid;
      grid-template-columns:1.2fr .8fr;
      gap:18px;
    }

    .grid-3{
      display:grid;
      grid-template-columns:repeat(3, 1fr);
      gap:18px;
    }

    .card{
      background:linear-gradient(180deg, rgba(8,15,31,.96), rgba(6,11,22,.96));
      border:1px solid var(--line);
      border-radius:26px;
      padding:20px;
      box-shadow:var(--glow);
    }

    .card-title{
      font-size:20px;
      font-weight:700;
      margin:0 0 14px;
    }

    .card-sub{
      color:var(--muted);
      font-size:13px;
      margin-bottom:16px;
    }

    label{
      display:block;
      color:#dce7ff;
      font-size:13px;
      margin-bottom:6px;
    }

    input, select, textarea{
      width:100%;
      padding:13px 14px;
      border-radius:16px;
      border:1px solid rgba(255,255,255,.10);
      background:rgba(255,255,255,.03);
      color:var(--text);
      outline:none;
      transition:.2s ease;
      font-size:14px;
    }

    textarea{
      min-height:120px;
      resize:vertical;
    }

    input:focus, select:focus, textarea:focus{
      border-color:rgba(110,168,255,.5);
      box-shadow:0 0 0 4px rgba(79,124,255,.12);
    }

    button{
      border:none;
      border-radius:16px;
      padding:13px 18px;
      font-weight:700;
      color:white;
      background:linear-gradient(135deg, var(--blue), #6f8dff);
      cursor:pointer;
      box-shadow:0 12px 30px rgba(79,124,255,.28);
      transition:transform .15s ease, opacity .2s ease;
    }

    button:hover{opacity:.95}
    button:active{transform:translateY(1px)}

    .button-row{
      display:flex;
      flex-wrap:wrap;
      gap:12px;
      margin-top:14px;
    }

    .table-wrap{
      overflow:auto;
      border-radius:18px;
      border:1px solid var(--line);
      background:rgba(255,255,255,.02);
    }

    table{
      width:100%;
      border-collapse:collapse;
      min-width:760px;
    }

    th, td{
      padding:14px 12px;
      border-bottom:1px solid rgba(255,255,255,.06);
      text-align:left;
      font-size:14px;
    }

    th{
      color:#c4d3f3;
      background:rgba(255,255,255,.02);
      font-weight:700;
    }

    tr:hover td{
      background:rgba(255,255,255,.02);
    }

    .msg{
      padding:12px 14px;
      border-radius:16px;
      background:rgba(52,211,153,.10);
      border:1px solid rgba(52,211,153,.22);
      color:#b7ffd8;
      margin-bottom:12px;
    }

    .danger{
      color:#ffb4b4;
    }

    .link-box{
      padding:14px;
      border-radius:18px;
      background:rgba(255,255,255,.03);
      border:1px solid var(--line);
      word-break:break-all;
    }

    .muted{color:var(--muted)}
    .mono{font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace}

    @media (max-width: 1100px){
      .hero-grid, .grid-3, .grid-2 { grid-template-columns:1fr 1fr; }
    }

    @media (max-width: 860px){
      .app-shell{ grid-template-columns:1fr; }
      .sidebar{ position:relative; top:auto; height:auto; }
      .hero-grid, .grid-3, .grid-2 { grid-template-columns:1fr; }
      .topbar{ flex-direction:column; align-items:flex-start; }
    }
  </style>
</head>
<body>
  <div class="app-shell">
    <aside class="sidebar">
      <div class="brand">
        <div class="brand-badge"></div>
        <div>NeuroBet</div>
      </div>

      <div class="nav-card">
        <div class="nav-title">Live Match</div>
        <div class="nav-big">{{ summary.matchup if summary else "NBA Game" }}</div>
        <div class="nav-sub">{{ summary.status if summary else "Live" }}</div>
      </div>

      <div class="nav-card">
        <div class="nav-title">Navigation</div>
        <div class="nav-links">
          <a href="/">Home</a>
          <a href="/admin">Admin Dashboard</a>
        </div>
      </div>
    </aside>

    <main class="main">
      {% block content %}{% endblock %}
    </main>
  </div>
</body>
</html>
"""

home_html = r"""
{% extends "base.html" %}
{% block content %}
<div class="topbar">
  <div>
    <div class="page-title">NBA Betting Platform</div>
    <div class="page-sub">Modern admin and player dashboards with separate access links.</div>
  </div>
  <div class="pill">Prototype Mode</div>
</div>

<div class="hero-grid">
  <div class="metric">
    <div class="metric-label">Current Matchup</div>
    <div class="metric-value">{{ summary.matchup }}</div>
    <div class="metric-note">Live betting dashboard</div>
  </div>
  <div class="metric">
    <div class="metric-label">Score</div>
    <div class="metric-value">{{ summary.score }}</div>
    <div class="metric-note">Updated by admin</div>
  </div>
  <div class="metric">
    <div class="metric-label">Quarter</div>
    <div class="metric-value">{{ summary.quarter }}</div>
    <div class="metric-note">Game progress</div>
  </div>
  <div class="metric">
    <div class="metric-label">Pot</div>
    <div class="metric-value">{{ summary.pot }}</div>
    <div class="metric-note">{{ summary.players_with_bets }} players active</div>
  </div>
</div>

<div class="grid-2">
  <div class="card">
    <div class="card-title">Welcome</div>
    <div class="card-sub">This is the main entry point of the app.</div>
    <p class="muted">Use the admin dashboard to create the game, generate player links, update scores, and settle bets.</p>
    <div class="button-row">
      <a href="/admin"><button>Open Admin Dashboard</button></a>
    </div>
  </div>

  <div class="card">
    <div class="card-title">System Overview</div>
    <div class="card-sub">Current public game data</div>
    <div class="link-box">
      <div><strong>Matchup:</strong> {{ summary.matchup }}</div>
      <div><strong>Score:</strong> {{ summary.score }}</div>
      <div><strong>Quarter:</strong> {{ summary.quarter }}</div>
      <div><strong>Status:</strong> {{ summary.status }}</div>
      <div><strong>Pot:</strong> {{ summary.pot }}</div>
      <div><strong>Players with Bets:</strong> {{ summary.players_with_bets }}</div>
    </div>
  </div>
</div>
{% endblock %}
"""

admin_html = r"""
{% extends "base.html" %}
{% block content %}
<div class="topbar">
  <div>
    <div class="page-title">Admin Dashboard</div>
    <div class="page-sub">Manage games, generate players, monitor bets, and settle results.</div>
  </div>
  <div class="pill">Admin Control Center</div>
</div>

{% if msg %}
<div class="msg">{{ msg }}</div>
{% endif %}

<div class="hero-grid">
  <div class="metric">
    <div class="metric-label">Total Pot</div>
    <div class="metric-value">{{ total_pot }}</div>
    <div class="metric-note">All active bets combined</div>
  </div>
  <div class="metric">
    <div class="metric-label">Admin Fees</div>
    <div class="metric-value">{{ admin_fees }}</div>
    <div class="metric-note">5% winnings fee</div>
  </div>
  <div class="metric">
    <div class="metric-label">Registered Players</div>
    <div class="metric-value">{{ registered_players }}</div>
    <div class="metric-note">Created access links</div>
  </div>
  <div class="metric">
    <div class="metric-label">Players with Bets</div>
    <div class="metric-value">{{ players_with_bets }}</div>
    <div class="metric-note">Active participation</div>
  </div>
</div>

<div class="grid-2">
  <div class="card">
    <div class="card-title">Game Overview</div>
    <div class="card-sub">Current public state</div>
    <div class="link-box">
      <div><strong>Matchup:</strong> {{ summary.matchup }}</div>
      <div><strong>Score:</strong> {{ summary.score }}</div>
      <div><strong>Quarter:</strong> {{ summary.quarter }}</div>
      <div><strong>Status:</strong> {{ summary.status }}</div>
    </div>
  </div>

  <div class="card">
    <div class="card-title">Settlement Overview</div>
    <div class="card-sub">Result summary</div>
    <div class="link-box">
      <div><strong>Winner:</strong> {{ game_state.winner or "-" }}</div>
      <div><strong>Settled At:</strong> {{ game_state.settled_at or "-" }}</div>
      <div><strong>Total Final Payouts:</strong> {{ total_payouts }}</div>
      <div><strong>Total Fee Collected:</strong> {{ admin_fees }}</div>
    </div>
  </div>
</div>

<div class="grid-3">
  <div class="card">
    <div class="card-title">Create / Reset Game</div>
    <form method="post" action="/admin/set_game">
      <label>Admin Password</label>
      <input type="password" name="password" required>

      <label>Team A</label>
      <input type="text" name="team_a" value="{{ game_state.team_a }}" required>

      <label>Team B</label>
      <input type="text" name="team_b" value="{{ game_state.team_b }}" required>

      <div class="button-row">
        <button type="submit">Set Game</button>
      </div>
    </form>
  </div>

  <div class="card">
    <div class="card-title">Update Score / Status</div>
    <form method="post" action="/admin/update_score">
      <label>Admin Password</label>
      <input type="password" name="password" required>

      <label>Score Team A</label>
      <input type="number" name="score_a" value="{{ game_state.score_a }}" required>

      <label>Score Team B</label>
      <input type="number" name="score_b" value="{{ game_state.score_b }}" required>

      <label>Quarter</label>
      <select name="quarter">
        {% for q in ["Not Started","Q1","Q2","Halftime","Q3","Q4","OT","Final"] %}
        <option value="{{ q }}" {% if game_state.quarter == q %}selected{% endif %}>{{ q }}</option>
        {% endfor %}
      </select>

      <label>Status</label>
      <select name="status">
        {% for s in ["Open for Betting","Closed","Settled"] %}
        <option value="{{ s }}" {% if game_state.status == s %}selected{% endif %}>{{ s }}</option>
        {% endfor %}
      </select>

      <div class="button-row">
        <button type="submit">Update Scoreboard</button>
      </div>
    </form>
  </div>

  <div class="card">
    <div class="card-title">Generate Player</div>
    <form method="post" action="/admin/create_player">
      <label>Admin Password</label>
      <input type="password" name="password" required>

      <label>Player Name</label>
      <input type="text" name="player_name" required>

      <div class="button-row">
        <button type="submit">Create Player Link</button>
      </div>
    </form>
  </div>
</div>

<div class="card">
  <div class="card-title">Player Links</div>
  <div class="card-sub">Generated player dashboards</div>
  {% if player_links %}
  <div class="table-wrap">
    <table>
      <tr><th>Name</th><th>Code</th><th>Link</th><th>Created</th></tr>
      {% for p in player_links %}
      <tr>
        <td>{{ p.name }}</td>
        <td class="mono">{{ p.code }}</td>
        <td><a href="{{ p.link }}" target="_blank">{{ p.link }}</a></td>
        <td>{{ p.created_at }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  <p class="muted">No players yet.</p>
  {% endif %}
</div>

<div class="card">
  <div class="card-title">All Bets</div>
  <div class="card-sub">Every active player bet</div>
  {% if all_bets %}
  <div class="table-wrap">
    <table>
      <tr><th>Name</th><th>Code</th><th>Team</th><th>Bet Amount</th><th>Time</th></tr>
      {% for b in all_bets %}
      <tr>
        <td>{{ b.name }}</td>
        <td class="mono">{{ b.code }}</td>
        <td>{{ b.team }}</td>
        <td>{{ b.bet_amount }}</td>
        <td>{{ b.time_added }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  <p class="muted">No bets yet.</p>
  {% endif %}
</div>

<div class="grid-2">
  <div class="card">
    <div class="card-title">Settle Results</div>
    <div class="card-sub">Choose the winner and finalize payouts</div>
    <form method="post" action="/admin/settle">
      <label>Admin Password</label>
      <input type="password" name="password" required>

      <label>Winner</label>
      <select name="winner">
        <option value="{{ game_state.team_a }}">{{ game_state.team_a }}</option>
        <option value="{{ game_state.team_b }}">{{ game_state.team_b }}</option>
      </select>

      <div class="button-row">
        <button type="submit">Settle Game</button>
      </div>
    </form>
  </div>

  <div class="card">
    <div class="card-title">Result Snapshot</div>
    <div class="card-sub">Current settlement state</div>
    <div class="link-box">
      <div><strong>Status:</strong> {{ game_state.status }}</div>
      <div><strong>Winner:</strong> {{ game_state.winner or "-" }}</div>
      <div><strong>Settled At:</strong> {{ game_state.settled_at or "-" }}</div>
      <div><strong>Total Payouts:</strong> {{ total_payouts }}</div>
      <div><strong>Total Fees:</strong> {{ admin_fees }}</div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-title">All Results</div>
  <div class="card-sub">Final payout computation for every player</div>
  {% if all_results %}
  <div class="table-wrap">
    <table>
      <tr><th>Name</th><th>Code</th><th>Status</th><th>Team</th><th>Bet</th><th>Gross Profit</th><th>Fee</th><th>Net Profit</th><th>Final Payout</th></tr>
      {% for r in all_results %}
      <tr>
        <td>{{ r.name }}</td>
        <td class="mono">{{ r.code }}</td>
        <td>{{ r.status }}</td>
        <td>{{ r.team }}</td>
        <td>{{ r.bet_amount }}</td>
        <td>{{ r.gross_profit }}</td>
        <td>{{ r.fee }}</td>
        <td>{{ r.net_profit }}</td>
        <td>{{ r.final_payout }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  <p class="muted">No results yet.</p>
  {% endif %}
</div>
{% endblock %}
"""

player_html = r"""
{% extends "base.html" %}
{% block content %}
<div class="topbar">
  <div>
    <div class="page-title">Player Dashboard</div>
    <div class="page-sub">Welcome back, {{ player.name }}.</div>
  </div>
  <div class="pill mono">{{ code }}</div>
</div>

{% if msg %}
<div class="msg">{{ msg }}</div>
{% endif %}

<div class="hero-grid">
  <div class="metric">
    <div class="metric-label">Current Matchup</div>
    <div class="metric-value">{{ summary.matchup }}</div>
    <div class="metric-note">Live game selected by admin</div>
  </div>
  <div class="metric">
    <div class="metric-label">Score</div>
    <div class="metric-value">{{ summary.score }}</div>
    <div class="metric-note">Current live score</div>
  </div>
  <div class="metric">
    <div class="metric-label">Quarter</div>
    <div class="metric-value">{{ summary.quarter }}</div>
    <div class="metric-note">Game progress</div>
  </div>
  <div class="metric">
    <div class="metric-label">Pot</div>
    <div class="metric-value">{{ summary.pot }}</div>
    <div class="metric-note">{{ summary.players_with_bets }} players active</div>
  </div>
</div>

<div class="grid-2">
  <div class="card">
    <div class="card-title">Place / Update Bet</div>
    <div class="card-sub">Choose the team you think will win</div>
    <form method="post" action="/player/{{ code }}/bet">
      <label>Pick Winning Team</label>
      <select name="selected_team">
        <option value="{{ game_state.team_a }}">{{ game_state.team_a }}</option>
        <option value="{{ game_state.team_b }}">{{ game_state.team_b }}</option>
      </select>

      <label>Bet Amount</label>
      <input type="number" step="0.01" name="bet_amount" value="1000" min="1000" required>
      <div class="muted" style="margin-top:8px;">Minimum bet: ₱{{ min_bet }}</div>

      <div class="button-row">
        <button type="submit">Save Bet</button>
      </div>
    </form>
  </div>

  <div class="card">
    <div class="card-title">Live Match Status</div>
    <div class="card-sub">Public information visible to players</div>
    <div class="link-box">
      <div><strong>Matchup:</strong> {{ summary.matchup }}</div>
      <div><strong>Score:</strong> {{ summary.score }}</div>
      <div><strong>Quarter:</strong> {{ summary.quarter }}</div>
      <div><strong>Status:</strong> {{ summary.status }}</div>
      <div><strong>Pot:</strong> {{ summary.pot }}</div>
      <div><strong>Players with Bets:</strong> {{ summary.players_with_bets }}</div>
    </div>
  </div>
</div>

<div class="grid-2">
  <div class="card">
    <div class="card-title">My Bet</div>
    <div class="card-sub">Your active bet details</div>
    {% if player_bet %}
      <div class="link-box">
        <div><strong>Selected Team:</strong> {{ player_bet.team }}</div>
        <div><strong>Bet Amount:</strong> {{ money(player_bet.bet_amount) }}</div>
        <div><strong>Time Added:</strong> {{ player_bet.time_added }}</div>
      </div>
    {% else %}
      <p class="muted">No active bet yet.</p>
    {% endif %}
  </div>

  <div class="card">
    <div class="card-title">My Result</div>
    <div class="card-sub">Shown after admin settles the game</div>
    {% if player_result %}
      <div class="link-box">
        <div><strong>Status:</strong> {{ player_result.status }}</div>
        <div><strong>Selected Team:</strong> {{ player_result.team }}</div>
        <div><strong>Bet Amount:</strong> {{ money(player_result.bet_amount) }}</div>
        <div><strong>Gross Profit:</strong> {{ money(player_result.gross_profit) }}</div>
        <div><strong>Fee Deducted:</strong> {{ money(player_result.fee) }}</div>
        <div><strong>Net Profit:</strong> {{ money(player_result.net_profit) }}</div>
        <div><strong>Final Payout:</strong> {{ money(player_result.final_payout) }}</div>
      </div>
    {% else %}
      <p class="muted">No result yet. Waiting for admin settlement.</p>
    {% endif %}
  </div>
</div>
{% endblock %}
"""

invalid_player_html = r"""
{% extends "base.html" %}
{% block content %}
<div class="topbar">
  <div>
    <div class="page-title danger">Invalid Player Link</div>
    <div class="page-sub">The requested dashboard does not exist.</div>
  </div>
  <div class="pill">404</div>
</div>

<div class="card">
  <div class="card-title">Access Code Not Found</div>
  <p class="muted">The access code <span class="mono">{{ code }}</span> does not exist.</p>
  <div class="button-row">
    <a href="/"><button>Go Home</button></a>
  </div>
</div>
{% endblock %}
"""

files = {
    "/content/templates/base.html": base_html,
    "/content/templates/home.html": home_html,
    "/content/templates/admin.html": admin_html,
    "/content/templates/player.html": player_html,
    "/content/templates/invalid_player.html": invalid_player_html,
}

for path, content in files.items():
    with open(path, "w", encoding="utf-8") as f:
        f.write(textwrap.dedent(content))

print("Modern UI templates updated.")

import subprocess, time, os

!pkill -f "uvicorn app:app" || true
!rm -f /content/app.log

proc = subprocess.Popen(
    ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8091"],
    cwd="/content",
    stdout=open("/content/app.log", "w"),
    stderr=subprocess.STDOUT,
)

time.sleep(4)
!tail -n 30 /content/app.log

!curl -I http://127.0.0.1:8091/
!curl -I http://127.0.0.1:8091/admin

!pkill cloudflared || true
!rm -f /content/cloudflared.log

import subprocess, time, re

cf = subprocess.Popen(
    ["/usr/local/bin/cloudflared", "tunnel", "--url", "http://localhost:8091"],
    stdout=open("/content/cloudflared.log", "w"),
    stderr=subprocess.STDOUT,
)

time.sleep(8)

log = open("/content/cloudflared.log", "r", encoding="utf-8").read()
print(log[-2000:])

match = re.search(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com", log)
if match:
    public_url = match.group(0)
    print("Public URL:", public_url)
    print("Admin URL:", public_url + "/admin")
else:
    print("Could not find public URL in cloudflared.log")

